### ISSUE TITLE
Infinitely loading and if refresh: 404 error

### ISSUE THREAD

**Issue by A-d-r-i** [Zoziologie/global-rare-ebird#2]
Hello,
I allow myself to raise some small bugs following some changes on the site (if I'm not mistaken).

1. access to the global rare ebird [http://zoziologie.raphaelnussbaumer.com/global-rare-ebird/](http://zoziologie.raphaelnussbaumer.com/global-rare-ebird/) works perfectly, but when you launch the search (by selecting a country): **infinite loading** // (_small note: the title of the page remains "See Your Observations"_)

2. if the current page is refreshed ( [http://zoziologie.raphaelnussbaumer.com/globalrareebird?r=FR](http://zoziologie.raphaelnussbaumer.com/globalrareebird?r=FR) ) :

![image](https://user-images.githubusercontent.com/27277698/111141013-4b91fa00-8583-11eb-8fc0-c0c3ade1e6ae.png)

That's it for me! I hope I can help. In any case, well done for these tools which work very well and are very useful! 😉

**Comment by Rafnuss** [comment]
Hi @A-d-r-i , thanks for your feedback. I haven't really checked all the new websites since they are hosted on github page directly (I use to have a OVH server but it has burn down).

I have made the correction (1f89ac7cfe35f3152d5f23172fa24e611755bdc1 588233f248948221cce06bc96f62147ce9bb7f9d 5713ef3fb2ffdeb90b1802af1f53f937ea1beaf6) and it seems to be working now. Let me know if you find any other bugs or if you have some suggestions.

**Comment by A-d-r-i** [comment]
It's perfect ! Everything is working normally now.
Thanks!
